name: Build Frontend and Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/e-power-generator-frontend/**'
      - 'backend/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && 
      (contains(github.event.pull_request.labels.*.name, 'force-build-frontend') || 
      (github.base_ref != 'main' && contains(github.event.pull_request.head.ref, 'frontend/')))) 



    steps:
      - name: 檢查程式碼
        uses: actions/checkout@v4

      - name: 設定 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 安裝依賴 (Frontend)
        run: |
          cd ./frontend/e-power-generator-frontend/
          npm install
          

      - name: 執行 lint 和 test (Frontend)
        run: |
          cd ./frontend/e-power-generator-frontend/
          npm run lint
          npm run test
      
      - name: 建置 (Frontend)
        run: |
          cd ./frontend/e-power-generator-frontend/
          npm run build

      - name: 上傳建置產物
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./frontend/e-power-generator-frontend/build

  build-backend:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && 
      (contains(github.event.pull_request.labels.*.name, 'force-build-backend') || 
      (github.base_ref != 'main' && contains(github.event.pull_request.head.ref, 'backend/'))))

    # defaults:
    #   working-directory: ./backend
      
    steps:
      - name: 檢查程式碼
        uses: actions/checkout@v4

      - name: 設定 Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: 執行 lint 和 test (Backend)
        run: |
          cd ./backend/
          go vet ./...
          go test ./...
      
      - name: 建置 (Backend)
        run: |
          cd ./backend
          go build -v ./cmd/server
        
      - name: 上傳建置產物
        uses: actions/upload-artifact@v4
        with:
          name: backend-binary
          path: ./backend/server
